dependencies {
    modImplementation(project(":modules:CTNH-Lib")){ transitive = false }
    jarJar(project(":modules:CTNH-Lib")){ transitive = false }

    modImplementation(ctnh.botarium)
    modImplementation(ctnh.creatediesel)
    modImplementation(ctnh.createvintage)
    
    modImplementation(ctnh.curios)
    modImplementation(ctnh.guideme)
    modImplementation(ctnh.ae2)
    modImplementation(ctnh.clothconfig)
    modImplementation(ctnh.ae2wt)
    modLocalRuntime(ctnh.constructionwand)

    modImplementation(ctnh.mantle)
}
