org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

minecraft_version = 1.20.1
forge_version = 47.4.1
mapping_channel = parchment
mapping_version = 2023.09.03

# Mod Properties
mod_version = 0.0.12
maven_group = com.mo_guang.ctpp
archives_base_name = CTPP
mod_id = ctpp
mod_name = CT++
mod_url = https://github.com/CTNH-Team/CTPP
mod_author = CTNH Team
mod_description = Compatible mod between GregTech-Modern and Create for the modpack Create: New Horizon
mod_license = LGPLv3
