# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Base properties
    # minecraft version
    minecraft_version=1.20.1
    # forge version, latest version can be found on https://files.minecraftforge.net/
    forge_version=47.4.1
    mapping_channel=parchment
    mapping_version=2023.09.03

# Mod Properties
    mod_version=0.0.10
    maven_group=com.mo_guang.ctpp
    archives_base_name=CT++
    mod_id=ctpp
    mod_name=CT++
    mod_url=
    mod_author=mo_guang
    mod_description=A mod for the compatibility between GTCEu and Create.
    mod_license=LGPL v3

# GregTech
    #gtceu_version=7.2.0
    ldlib_version=1.0.42
    registrate_version=MC1.20-1.3.11
    configuration_version=2.2.0

# XEI
    #jei_version=15.20.0.105
    #emi_version = 1.1.13

#Create
    create_version=6.0.6-168
    flywheel_version=1.0.4
    ponder_version=1.0.78

#Ad-astra
    resourcefullib_version=2.1.28
    resourcefulconfig_version=2.1.2
    botarium_version=2.3.4
    ad_astra_version=1.15.20

#EIO
    graphlib_version=3.0.4
    enderio_version=1.20.1-6.2.15-beta

#kubejs
    kubejs_version=2001.6.5-build.14
    rhino_version=2001.2.3-build.6
    architectury_version=9.2.14

#Magic
    curios_version=5.9.1+1.20.1
    bloodmagic_version=KFYCrtLV
    libx_version=5.0.12
    geckolib_version=4.4.9
    botania_version=1.20.1-450-FORGE
    arsnouveau_version = 4.12.7.264

    ae2_version=15.4.8

